function onOpen() {
  const ui = SpreadsheetApp.getUi();
  const dbMenu = ui.createMenu('🗄️ Database Archive')
    .addItem('Configure Railway Database', 'configureArchiveDatabase')
    .addItem('Test Railway + Torn Connection', 'testRailwayTornConnection')
    .addItem('Refresh War Archive Index', 'refreshWarArchiveIndex')
    .addItem('Load Selected Prior War', 'loadSelectedArchivedWar')
    .addItem('Load Prior War by ID', 'loadArchivedWarByIdPrompt')
    .addItem('Clear Current Payout Snapshot (TEST)', 'clearCurrentArchiveSnapshotForTest')
    .addSeparator()
    .addItem('Save Current War to Database', 'archiveCurrentWarToDatabase')
    .addItem('Publish Current Payout to Web', 'publishCurrentPayoutToWeb')
    .addItem('Publish Selected Archived War to Web', 'publishSelectedArchivedWarToWeb')
    .addItem('Show Public Web URL', 'showPublicPayoutWebUrl')
    .addSeparator()
    .addItem('Migrate Legacy Google Archives', 'migrateLegacyGoogleArchivesToDatabase')
    .addItem('Migrate Public-Only Payout Tabs', 'migrateLegacyPublicOnlyWarsToDatabase')
    .addSeparator()
    .addItem('ARCHIVE TO DATABASE & RESET', 'archiveAndResetWarDatabase');

  ui.createMenu('⚔️ Faction Tools')
    .addItem('1. Quick Refresh Dashboard Data', 'refreshDashboard')
    .addItem('2. Update Faction Roster', 'updateRoster')
    .addItem('3. Initialize Bounty Tracker', 'setupBountyTracker')
    .addSubMenu(
      ui.createMenu('🎯 Bounties')
        .addItem('Configure Bounty Bot Bridge', 'configureBountyBotBridge')
        .addItem('Scan Current War Bounties', 'triggerCurrentWarBountyScan')
        .addItem('Check Current War Bounty Scan', 'checkCurrentWarBountyScanStatus')
    )
    .addSeparator()
    .addItem('4. Select Official Reports', 'showOfficialReportPicker')
    .addItem('5. Fetch Official Torn Reports', 'fetchOfficialReports')
    .addItem('6. Pull Raw Attack Data', 'importWarData')
    .addItem('7. Generate Payout Tab', 'buildPayoutTab')
    .addItem('8. Calculate Payout Metrics', 'runPayoutMath')
    .addItem('Apply Selected Payout Preset', 'applySelectedPayoutPreset')
    .addItem('9. Generate Final Payouts', 'buildFinalPayoutTab')
    .addItem('10. Publish Payout to Public Sheet (Legacy)', 'publishPayoutToPublic')
    .addSeparator()
    .addSubMenu(dbMenu)
    .addSeparator()
    .addItem('11. Log War to History', 'logWarToHistory')
    .addItem('Legacy Google Sheet Archive & Reset', 'archiveAndResetWar')
    .addItem('🧪 Test Legacy Archive (No Reset)', 'testArchiveOnly')
    .addItem('🧹 Clean Sweep (Reset Sheet)', 'cleanSweep')
    .addSeparator()
    .addItem('🔍 Run Auto-Auditor', 'runPayoutAudit')
    .addItem('Rebuild Dashboard UI', 'buildDashboard')
    .addToUi();
}
