function onOpen() {
  const ui = SpreadsheetApp.getUi();
  const dbMenu = ui.createMenu('🗄️ Database Archive')
    .addItem('Configure Railway Database', 'configureArchiveDatabase')
    .addItem('Refresh War Archive Index', 'refreshWarArchiveIndex')
    .addItem('Load Selected Prior War', 'loadSelectedArchivedWar')
    .addItem('Load Prior War by ID', 'loadArchivedWarByIdPrompt')
    .addSeparator()
    .addItem('Save Current War to Database', 'archiveCurrentWarToDatabase')
    .addItem('Migrate Legacy Google Archives', 'migrateLegacyGoogleArchivesToDatabase')
    .addSeparator()
    .addItem('ARCHIVE TO DATABASE & RESET', 'archiveAndResetWarDatabase');

  ui.createMenu('⚔️ Faction Tools')
    .addItem('1. Quick Refresh Dashboard Data', 'refreshDashboard')
    .addItem('2. Update Faction Roster', 'updateRoster')
    .addItem('3. Initialize Bounty Tracker', 'setupBountyTracker')
    .addSeparator()
    .addItem('4. Fetch Official Torn Reports', 'fetchOfficialReports')
    .addItem('5. Pull Raw Attack Data', 'importWarData')
    .addItem('6. Generate Payout Tab', 'buildPayoutTab')
    .addItem('7. Calculate Payout Metrics', 'runPayoutMath')
    .addItem('8. Generate Final Payouts', 'buildFinalPayoutTab')
    .addItem('9. Publish Payout to Public Sheet (Legacy)', 'publishPayoutToPublic')
    .addSeparator()
    .addSubMenu(dbMenu)
    .addSeparator()
    .addItem('10. Log War to History', 'logWarToHistory')
    .addItem('Legacy Google Sheet Archive & Reset', 'archiveAndResetWar')
    .addItem('🧪 Test Legacy Archive (No Reset)', 'testArchiveOnly')
    .addItem('🧹 Clean Sweep (Reset Sheet)', 'cleanSweep')
    .addSeparator()
    .addItem('🔍 Run Auto-Auditor', 'runPayoutAudit')
    .addItem('Rebuild Dashboard UI', 'buildDashboard')
    .addToUi();
}
